img_size: 224
resize_size: 256

train:
  crop_scale_min: 0.8
  crop_scale_max: 1.0
  hflip_p: 0.5
  rotation_deg: 10
  jitter:
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
    hue: 0.02

normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
